export const ALLSUBCATEGORIES = "ALLSUBCATEGORIES"
export const ALLCOLORS = "ALLCOLORS"
export const ALLBRANDS = "ALLBRANDS"
export const ALLSIZES = "ALLSISEZ"
export const ALLCATEGORIES = "ALLCATEGORIES"
export const ALLPRODUCTS = "ALLPRODUCTS"
export const SELECTEDCATEGORY = "SELECTEDCATEGORY"
export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const PRODUCTS_DETAIL = 'PRODUCTS_DETAIL'
export const PRODUCTS_FILTERED = 'PRODUCTS_FILTERED'
export const POST_FAVORITES_API = 'POST_FAVORITES_API'
export const POST_FAVORITES_API_INICIO = 'POST_FAVORITES_API_INICIO'
export const POST_FAVORITES_LS = 'POST_FAVORITE_LS'
export const DELETE_FAVORITES = 'DELETE_FAVORITES'
export const DELETE_FAVORITES_API = 'DELETE_FAVORITES_API'
export const PRODUCTOS = 'PRODUCTOS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const CART_PRODUCTS = 'CART_PRODUCTS'
export const GETPRODUCT_BYNAME = 'GETPRODUCT_BYNAME'
export const POST_CART_LS = 'POST_CART_LS'
export const DELETE_CART_LS = 'DELETE_CART_LS'
export const EMPTY_LOCAL_CART = 'EMPTY_LOCAL_CART';
export const DELETE_ART_LS = "DELETE_ART_LS";
export const POST_CART_API = 'POST_CART_API';
export const DEL_ART_API = 'DEL_ART_API';
export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS'
export const GET_ALL_VENTAS = 'GET_ALL_VENTAS'
export const GET_USER_COMPRAS = 'GET_USER_COMPRAS'
export const GET_REVIEWRS = 'GET_REVIEWRS'
export const CLEAN_PREVIEW = 'CLEAN_PREVIEW'
export const POST_ART_API = 'POST_ART_API';
export const GET_NAME = 'GET_NAME'





//provisional
export const COPY_ALLPRODUCTS = 'COPY_ALLPRODUCTS'

